project_id = "uxojubleolviktarveyy"

[functions.generate-ebook-title]
verify_jwt = false

[functions.generate-ebook-content]
verify_jwt = false

[functions.generate-ebook-cover]
verify_jwt = false

[functions.whop-webhook]
verify_jwt = false